Transform: AWS::Serverless-2016-10-31
Resources:
  EventBridgeToToSnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref UsersSNSTopic
      Topics:
        - !Ref UsersSNSTopic
  MarketplaceCustomEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: marketplace
  MarketplaceAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: MarketplaceAPI
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /request/{id}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRequestsFunction.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateRequestsFunction.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  GetRequestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetRequestsFunction
      CodeUri: src/GetRequestsFunction
      Handler: handler.handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          TABLE_NAME: !Ref requests
          TABLE_ARN: !GetAtt requests.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref requests
      Events:
        MarketplaceAPIGETrequestid:
          Type: Api
          Properties:
            Path: /request/{id}
            Method: GET
            RestApiId: !Ref MarketplaceAPI
  GetRequestsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetRequestsFunction}
  UpdateRequestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateRequestsFunction
      CodeUri: src/UpdateRequestsFunction
      Handler: handler.handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          TABLE_NAME: !Ref requests
          TABLE_ARN: !GetAtt requests.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref requests
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource:
                - !GetAtt MarketplaceCustomEventBus.Arn
      Events:
        MarketplaceAPIPOSTrequestid:
          Type: Api
          Properties:
            Path: /request/{id}
            Method: POST
            RestApiId: !Ref MarketplaceAPI
  UpdateRequestsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateRequestsFunction}
  requests:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  Update3rdPartyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Update3rdPartyFunction
      CodeUri: src/Update3rdPartyFunction
      Handler: handler.handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
  Update3rdPartyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Update3rdPartyFunction}
  UpdateInstitutionToUpdate3rdPartyFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Update3rdPartyFunction.Arn
      Principal: !Sub events.${AWS::URLSuffix}
      SourceArn: !GetAtt Update3rdPartyFunction.Arn
  ThirdrdPartyAPI:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ThirdrdPartyAPI
      CodeUri: src/3rdPartyAPI
      Handler: handler.handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables: {}
  ThirdrdPartyAPILogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ThirdrdPartyAPI}
  ToThirdrdPartyAPIWitsToInstitutionAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ThirdrdPartyAPI.Arn
      Principal: !Sub events.${AWS::URLSuffix}
      SourceArn: !GetAtt To3rdParty2API.Arn
  ToThirdrdPartyAPIUnisaToInstitutionAPIPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ThirdrdPartyAPI.Arn
      Principal: !Sub events.${AWS::URLSuffix}
      SourceArn: !GetAtt To3rdParty1API.Arn
  UsersSNSTopic:
    Type: AWS::SNS::Topic
  To3rdParty1API:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        detail:
          institute:
            - 3rdParty1
      EventBusName: marketplace
      Targets:
        - Id: !Ref ThirdrdPartyAPI
          Arn: !GetAtt ThirdrdPartyAPI.Arn
  To3rdParty2API:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        detail:
          institute:
            - 3rdParty2
      EventBusName: marketplace
      Targets:
        - Id: !Ref ThirdrdPartyAPI
          Arn: !GetAtt ThirdrdPartyAPI.Arn
  ThirdPartytoMarketplaceSNS:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        Source:
          - com.marketplace.3rdparty1
        DetailType:
          - marketplace status update
        detail:
          institute:
            - 3rdparty1
      Targets:
        - Id: UsersSNSTopic
          Arn: !Ref UsersSNSTopic
      EventBusName: marketplace
  Update3rdParty:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.health
      Targets:
        - Id: !Ref Update3rdPartyFunction
          Arn: !GetAtt Update3rdPartyFunction.Arn
      EventBusName: marketplace
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: EventBridge
      Members:
        - MarketplaceCustomEventBus
        - Update3rdParty
        - ThirdPartytoMarketplaceSNS
        - To3rdParty2API
        - To3rdParty1API
    Group2:
      Label: Group2
      Members:
        - UpdateInstitutionToUpdate3rdPartyFunctionPermission
        - Update3rdPartyFunction
    Group3:
      Label: EventGateway
      Members:
        - MarketplaceAPI
        - GetRequestsFunction
        - UpdateRequestsFunction
        - requests